name = "russ-rest"
main = "src/index.ts"
compatibility_date = "2024-11-29"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

# Custom domains
routes = [
  { pattern = "www.russ.rest", zone_name = "russ.rest", custom_domain = true },
  { pattern = "russ.rest", zone_name = "russ.rest", custom_domain = true }
]

[vars]
DEFAULT_USERNAME = "russmckendrick"

# Development environment
[env.dev]
vars = { DEFAULT_USERNAME = "russmckendrick" }

# Production environment
[env.production]
routes = [
  { pattern = "www.russ.rest/*", zone_name = "russ.rest" }
]
